server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  activiti:
    check-process-definitions: false
